import React from 'react'

function neverVisitedLP() {
    return (
        < div className={styles.container} >
            <Head>
                <title>Future Criteria</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Enter words that describe your future life:
                </h1>
                <form>
                    <input className={styles.input} type="text" size={100} onChange={handleChange} placeholder='criteria for your future' required></input>

                    <button type="button" onClick={() => textValue ? router.push("/table-page") : null}>Done</button>
                </form>
            </main>
            )
        </div>
}

export default neverVisitedLP