import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import Link from 'next/link'
import React from 'react'
import { useColumns } from '../components/context/global'
import { useRouter } from 'next/router'



export default function Home() {


  const router = useRouter()

  const [isSSR, setSSR] = useState(true) //isSSR is keeping track of whether we are Server Side Rendering or not

  useEffect(() => {
    // set to false, essentially telling it we are in the client
    //the empty [] tells means that as soon as the client is open set isSSR to false
    setSSR(false)
    const storageColumns = localStorage.getItem("columns")
    if (storageColumns != null) {
      console.log("storageColumns.length=", storageColumns.length)
    }
    if (storageColumns != null && storageColumns.length > 62) { //16 is a oddly specific num don't knwo where it is coming from
      router.push("/table-page")
    }
  }, [])

  const [textValue, setTextValue] = useState()
  function handleChange(e) { //onChange event
    setTextValue(e.target.value) // extract the value from the target that triggered an event
  }

  //need to find a way to export columnHeaders so that it can be imported in table-page.js and passed as an
  // argument to the createColumns function
  const { columnHeaders, setcolumnHeaders } = useColumns()



  // useEffect(() => {
  //   if (textValue != null) {
  //     const splitted = textValue.split(',')
  //     setcolumnHeaders(splitted)
  //   }
  // }, [textValue])
  //idea: use the Context idea to export these variables https://dev.to/nazmifeeroz/using-usecontext-and-usestate-hooks-as-a-store-mnm
  useEffect(() => {
    if (columnHeaders.length)
      localStorage.setItem("columns", JSON.stringify(columnHeaders))

  }
    , [columnHeaders])

  const reroute = () => { textValue ? router.push("/table-page") : null }


  //when the "Done" button is clicked split textValue and merge splitted to the current state of ColumnHeaders
  //then reroute
  const handleClick = () => {
    if (textValue) {
      const splitted = textValue.split(',')
      setcolumnHeaders([...columnHeaders, ...splitted])//this is how you merge an array with your current array state using set...
      reroute()
    }
    else {

    }

  }

  function handleKeyDown(e) {
    console.log('User pressed: ', e.key)
    if (e.key === 'Enter') {
      handleClick()
    }
  }

  return (
    <div className='bg-primary opacity-100'>

      <div>

      </div>
      < div className={styles.container} >
        <Head>
          <title>Future Criteria</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className='display: flex flex-col items-center'>
            <div className='basis-2'>
              <h1 className='font-family:Outfit font-style: font-semibold text-primary-font capitalize text-8xl'>
                What college means to you:
              </h1>
            </div>
            <div onKeyDown={(e) => handleKeyDown(e)}>
              <Link href="/question1">
                <button type="button" onClick={handleClick} className='mt-4 text-primary-font bg-button p-2 rounded-lg opacity-90 font-mono hover:bg-gradient-to-r from-light-purple to-dusty-pink'>Take Survey</button>
              </Link>
            </div>
          </div>
          {/*add an onClick event here maybe???*/}

          {/* <ul>{lstOfWords?.map((value,index)=>{
                  if (value === ""){
                    return
                  }
                  return <li key={index}>{value}</li>
              })}</ul> */}
        </main>

      </div >
    </div>
  )
}



