import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import Link from 'next/link'

export default function Home() {
  const [textValue, setTextValue] = useState("")
  function handleChange (e) { //onChange event
    setTextValue(e.target.value) // extract the value from the target that triggered an event
  }
  const [lstOfWords, setLstOfWords] = useState()
  useEffect(() => {
    const splitted = textValue.split(',')
    setLstOfWords(splitted)
  }, [textValue])

  return (
    <div className={styles.container}>
      <Head>
        <title>Future Criteria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Enter words that describe your future life:
        </h1>
        <input className={styles.input} type= "text" size= {100} onChange= {handleChange} placeholder='criteria for your future'  ></input>


        <Link href= "table-page">
            <a><button>Done</button></a>
        </Link>

        
        <ul>{lstOfWords?.map((value,index)=>{
            if (value === ""){
              return
            }
            return <li key={index}>{value}</li>
        })}</ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
