import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import { NodeNextRequest } from 'next/dist/server/base-http/node'

const Home = () => {
    const [textValue, setTextValue] = useState()
    const [answers, setAnswers] = useState([])
    const [counter, setCounter] = useState(0)

    function handleChange(e) { //onChange event
        setTextValue(e.target.value) // extract the value from the target that triggered an event
    }
    const router = useRouter()
    const reroute = () => { counter == questions.length - 1 ? router.push("/define-criteria") : null }

    const questions = [
        {
            question: "What size of school are you looking for?",
            extraText: "Small (< 5000), Medium (> 5000 , < 15000), Big (> 15,000)",
            inputType: "text"
        },
        {
            question: "What type of extra curricular activities are you interested in?",
            extraText: null,
            inputType: "text"
        },
        {
            question: "What kind of campus atmosphere are you looking for?",
            extraText: null,
            inputType: "text"
        },
        {
            question: "What types of majors and classes are you interested in?",
            extraText: null,
            inputType: "text"
        },
        {
            question: "What do you hope to gain from your college experience?",
            extraText: null,
            inputType: "text"
        }]


    //when the "Done" button is clicked split textValue and merge splitted to the current state of ColumnHeaders
    //then reroute
    const handleClick = () => {
        if (textValue) {
            setAnswers([...answers, textValue])
            console.log("answer1,", answers)
            setCounter(counter + 1)
            setTextValue('')
            //localStorage.setItem("answers", JSON.stringify(textValue))
            //this is how you merge an array with your current array state using set...
            reroute()
        }
        else {

        }

    }

    while (counter < questions.length) {
        return <div>
            <div className='bg-primary opacity-100'>

                <div>

                </div>
                < div className={styles.container} >
                    <Head>
                        <title>Question {counter + 1}</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>

                    <main className={styles.main}>
                        <div className='display: flex flex- items-center'>
                            <div>
                                <h1 className='text-primary-font font-family:Outfit font-style: font-semibold text-indigo-900 capitalize text-8xl'>
                                    {questions[counter].question}
                                </h1>
                                <br></br>
                                {(questions[counter].extraText) ?
                                    <h3 className='text-primary-font opacity-50 font-family:Outfit font-style: font-semibold text-indigo-900 capitalize text-2xl'>
                                        {questions[counter].extraText}
                                    </h3> : null
                                }

                            </div>
                            <div>
                                <form>
                                    <input key={counter} className='mr-48 rounded-full box-border h-10 w-9/12 p-4 bg-input-colour centre text-white ' type="text" size={100} onChange={handleChange} placeholder='answer here' required></input>
                                    <button type="button" onClick={handleClick} className=' font-mono mt-2.5 text-primary-font bg-button p-1.5 rounded-lg bg-button hover:bg-gradient-to-r from-light-purple to-sea-green '>Next</button>

                                </form>
                            </div>
                        </div>
                    </main>
                </div >
            </div >
        </div >
    }
}
export default Home
